on: push
jobs:
  Build:
    runs-on: ubuntu-latest
container: gradle:6-jdk11

steps:
- name: Clone-down
  uses: actions/checkout@v2

 - run: chmod +x github-actions-katas/ci/build-app.sh && github-actions-katas/ci/build-app.sh
